// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUvcCIHoi6l8RjdnLS-60Y97wKMDxSJWI',
    appId: '1:1078071122277:web:0603e2e4080aacb900298c',
    messagingSenderId: '1078071122277',
    projectId: 'fitness-app-bc7a5',
    authDomain: 'fitness-app-bc7a5.firebaseapp.com',
    storageBucket: 'fitness-app-bc7a5.firebasestorage.app',
    measurementId: 'G-SDL48DDX42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgUcEXo47_Pdy3szWXq_2osDBibEtdhJ4',
    appId: '1:1078071122277:android:1a2a7ab202e4f72c00298c',
    messagingSenderId: '1078071122277',
    projectId: 'fitness-app-bc7a5',
    storageBucket: 'fitness-app-bc7a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZEvHy1eaerzhaTrlJOdXZjLrLjbDifgM',
    appId: '1:1078071122277:ios:ff65ff50b7e5675400298c',
    messagingSenderId: '1078071122277',
    projectId: 'fitness-app-bc7a5',
    storageBucket: 'fitness-app-bc7a5.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUvcCIHoi6l8RjdnLS-60Y97wKMDxSJWI',
    appId: '1:1078071122277:web:251edefd380adc4900298c',
    messagingSenderId: '1078071122277',
    projectId: 'fitness-app-bc7a5',
    authDomain: 'fitness-app-bc7a5.firebaseapp.com',
    storageBucket: 'fitness-app-bc7a5.firebasestorage.app',
    measurementId: 'G-BPZEDRYHQ9',
  );
}
