// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyHr43kATsuh5c8yxtsnSZwMUafaza85s',
    appId: '1:58661381064:android:9f2bc244712dfab79b16fd',
    messagingSenderId: '58661381064',
    projectId: 'fittrack-f1c0d',
    storageBucket: 'fittrack-f1c0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsmCTsYPp6cm3QX8xDrj20y0WRPMd1FRc',
    appId: '1:58661381064:ios:b1918f447a75411b9b16fd',
    messagingSenderId: '58661381064',
    projectId: 'fittrack-f1c0d',
    storageBucket: 'fittrack-f1c0d.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMenGtRdFu-S2jvTWaJ9G3tnjwuhYyHqQ',
    appId: '1:58661381064:web:9dc527c0c9782a419b16fd',
    messagingSenderId: '58661381064',
    projectId: 'fittrack-f1c0d',
    authDomain: 'fittrack-f1c0d.firebaseapp.com',
    storageBucket: 'fittrack-f1c0d.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsmCTsYPp6cm3QX8xDrj20y0WRPMd1FRc',
    appId: '1:58661381064:ios:b1918f447a75411b9b16fd',
    messagingSenderId: '58661381064',
    projectId: 'fittrack-f1c0d',
    storageBucket: 'fittrack-f1c0d.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMenGtRdFu-S2jvTWaJ9G3tnjwuhYyHqQ',
    appId: '1:58661381064:web:92da0f60846a7fbc9b16fd',
    messagingSenderId: '58661381064',
    projectId: 'fittrack-f1c0d',
    authDomain: 'fittrack-f1c0d.firebaseapp.com',
    storageBucket: 'fittrack-f1c0d.firebasestorage.app',
  );

}